version: '3.8'

# WebAgent Docker Compose - Supporting Services Only
# Development is done on host machine, not in containers
# Use: docker-compose up -d postgres redis

services:
  # Optional: App container for production deployment only
  # For development, run the app directly on host machine
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://${POSTGRES_USER:-webagent}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-webagent}
      - ASYNC_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-webagent}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-webagent}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - uploads:/app/uploads
      - screenshots:/app/screenshots
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - webagent-network
    profiles:
      - production  # Only start with --profile production

  # PostgreSQL Database - Supporting Service
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-webagent}
      - POSTGRES_USER=${POSTGRES_USER:-webagent}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - webagent-network

  # Redis Cache - Supporting Service
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - webagent-network

  # Optional: Database admin interface
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@webagent.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-changeme}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - webagent-network
    profiles:
      - tools

  # Optional: Redis admin interface
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - webagent-network
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:
  uploads:
  screenshots:

networks:
  webagent-network:
    driver: bridge